services:
  app:
    build: .
    container_name: crud-planilhas-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - laravel

  nginx:
    image: nginx:1.27
    container_name: crud-planilhas-nginx
    ports:
      - "8080:80" # http://localhost:8080
    volumes:
      - ./:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:15
    container_name: crud-planilhas-db
    environment:
      POSTGRES_DB: crud_planilhas
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql/data
    # Usa 5433 no host para não bater com o PostgreSQL instalado na máquina
    ports:
      - "5433:5432"
    networks:
      - laravel

networks:
  laravel:

volumes:
  db-data:
